### PR TITLE
Fix for the issue #2652

### PR DESCRIPTION
**Pull request by Wolf2323**
This should fix the related issue.

In the first commit i break the format again so i make a second so fix the format

### CODE REVIEW

**Comment by LlmDl** [comment]
While this should fix the bug it doesn't fix the fact there's a townblock with no town. Rather than recording the townblock having a blank town it should not be saved.

**Comment by Wolf2323** [comment]
Do i understand it correctly? you want to remove townblocks without a town?

**Comment by LlmDl** [comment]
That is correct, I don't know how coolsurdy has them when flatfile already has code that removes no-town townblocks. 

They appear in game as blocks that cannot be claimed by towns but are also not considered wilderness. They used to happen sometimes when towns were deleted.

If you would like to have it delete the townblock and then test that it's working properly that would be good.

**Comment by Wolf2323** [comment]
I loked again in the Code. I think the old Code is correct, and the townblocks should be saved correctly.
The only thing is, that a person who dont know exactly what the error means, think there is a error but it is only a information, that there war a townblock without a town and that could be ignored in the most situations.

**Comment by LlmDl** [comment]
Please test your code and let me know how it works. Hopefully the error is only shown once and upon restart is not seen again because the townblock wasnt saved.

**Comment by Wolf2323** [comment]
II tried to test this, but when i remove the town in the file the file is deleted before the plugin convert it to MySQL.

**Comment by Wolf2323** [comment]
i close this, because i can't see that this fix the problem.
The problem i have i cant reproduce the bug

**Pull request closed without merging**
