### PR TITLE
Add Reserve Support.

### PR DESCRIPTION
**Pull request by creatorfromhell**

### CODE REVIEW

**Comment by LlmDl** [comment]
Before I accept this I'll need the Reserve.jar so I can add it to our libs folder. Can you link me the proper jar file?

**Comment by creatorfromhell** [comment]
https://gofile.io/?c=sEWBjz

**Comment by LlmDl** [comment]
That link did not work. Can you rehost it?

**Comment by creatorfromhell** [comment]
[Reserve.zip](https://github.com/LlmDl/Towny/files/1726210/Reserve.zip)

**Pull request merged**
