### PR TITLE
Improove the german Translation

### PR DESCRIPTION
**Pull request by Wolf2323**
The made changes by Articdive in the german translation are not perfect. My translation are much better and grammatically correct

### CODE REVIEW

**Comment by Articdive** [comment]
Für Deutsche bzw. Österreicher:  
1. Tun ist umgangssprachlich.
2. Es wird "dieser" stadt genommen, weil dass bald generisch für andere Städte sein soll, und admins andere Städte den pvp status wechseln können.
3. Es gibt keine grammatikalischen Fehlern.

For English speakers:
1. "Tun" is colloquial
2. I made a mistake in the english.yml by saying "your" town instead of "this town", which i will change, I believe it should be done so that we keep it generic in case Admins change the pvp status.
3. There are no grammatically incorrect sentences. I was using the "Höflichtkeitsform" also known as "courtesy naming", its where we address an unknown person as "Sie" instead of You, sorta like in English when you say "Mr." instead of "you" (kinda hard to translate, since then all pronouns get changed into courtesy pronouns.).

We are and will continue using the variant of "Hochdeutsch" the German taught in all Gymnasiums in Germany, keep it generic and that everyone will understand, the word "tun" is not used by all german regions however the word "umsetzen" is, "tun" is "Hochdeutsch" but not under any means necessary here, "umsetzten" is a very functional, completely legitimate word to use here and it is by all means not a mistake, if I was lazy i would have wrote "tun" there, it is stylistically bad to use "tun", which is why I avoid it . 

Side Note: I have no objection to taking your translation, but please 1. correct your English mistakes before you ramble on about my "mistakes". 2. Don't say i did "grammatical" mistakes when mistaking the addressee is clearly not even all that wrong, since we don't know the addressee the "courtesy naming" should take place. 3.Your translations are by all means not "much better and grammatically correct", sure you corrected 1 mistake I did while doing the english.yml and german.yml.

Ramble completed , Don't take it too serious, if you have an addition or change feel free to add it, but don't call me incorrect or incompetent, and please label the mistakes correctly if you even want to complain about it, but it is by all means not necessary when you complain about it to call certain people incorrect.

**Comment by Wolf2323** [comment]
'&cDer Spieler %s ist noch nicht auf dem Server lang genug um eingeladen zu werden, bitte warten Sie.'
ist grammatikalisch falsch und bitte usw wird nirgends in der language verwendet

**Comment by Wolf2323** [comment]
1. you right i was a little bit too fast. i changed it back
2. The translation sounds weird and i looked in the english one and there stand you. but if you make the mistake in the english one and you mean 'dieser', its ok . So i changed it back.
3. Sorry but your german is not the best one. And there are grammatical mistakes.

"Sie" or "Mr." is something that is never used in the entire translation. So it is a break in the style of the translation. Also we never use something like "bitte, danke" "please, thanks" in the translation becaure its not necessary.

**Comment by Articdive** [comment]
Wechsel es zu "deiner" Stadt und nicht "dieser", mein Fehler, da ich nicht in Acht genommen habe, dass einer von eine andere Stadt "/t toggle pvp" schreiben kann.

**Comment by Articdive** [comment]
Once he changes the "deiser" to "deiner" in the 4th last line (i think) this should be good to accept.

**Pull request merged**
