### PR TITLE
A good german translation

### PR DESCRIPTION
**Pull request by Wolf2323**
i have found very bad translations and a couple of translations was missing

### CODE REVIEW

**Comment by Articdive** [comment]
My testing has shown that the umlauts ( ü , ö , ä ) do actually work with the YAML Loader & Minecraft in game chat

**Comment by Wolf2323** [comment]
@LlmDl  fore some unknown reasons the Translation does not work correctly, because üäöß are not correctly shown. In the Test it has worked. I look if i can find any solution, but if someone can help me would this be nice

**Comment by Articdive** [comment]
Hmm seems like the umlauts Sometimes copy over and sometimes don't when forcing the german.yml out of the jar file.
Just tested it out and got 1 file where it worked and 2 where it didn't.
So somehow charcters get changed during the copy from the jar file to the settings folder,
But then the norwegian, spanish and other language files should do the same...?

**Comment by Wolf2323** [comment]
When i replace the copied file in the settings folder it works all fine
this means there should be a problem by writing/copying the original file with utf8

**Pull request merged**
