### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by Wolf2323**
this is mainly a german translation, but to translate this i needed to add an argument to you_have_been_invited_to_join and you_have_been_requested_to_ally

### CODE REVIEW

**Comment by LlmDl** [comment]
I see why you've changed the language string to what you have but since the language file is already out and some people have already updated it would cause an error anytime they get an invite. Is there no german way of asking the question with the town name on the end?

**Comment by Wolf2323** [comment]
not that i know, i thought about it round about 20 minutes. The result was no, and i thought , that other languages could have the same problem.

**Comment by LlmDl** [comment]
In that case we'll need a new language string. If you want to add a new line to the bottom of the file: you_have_been_invited_to_join2 put your versions into it. I'll take it and bump the file version numbers and get it out ASAP.

**Comment by Wolf2323** [comment]
Alternatively i can add a if statement, that checks, if the string contains a %s and if not i append it to the end

**Comment by LlmDl** [comment]
That would set a bad precedent, there's no real reason to not have the town/nation name inside of the language string, especially if there's languages that aren't ordered like english.

**Comment by Wolf2323** [comment]
all work is done

**Comment by LlmDl** [comment]
Nice work it's part of 0.92.0.6

**Pull request merged**
