### PR TITLE
Update spanish.yml

### PR DESCRIPTION
**Pull request by SeDark**
* Update spanish.yml

### CODE REVIEW

**Comment by LlmDl** [comment]
What sort of spanish do you speak? Which country are you from?

**Comment by SeDark** [comment]
I speak Spanish from Spain, I'm from Madrid (Spain).

**Comment by LlmDl** [comment]
Excellent.

**Comment by SeDark** [comment]
There are certain words that should not be translated as "claim", which in Spanish is "reclamar" or "demandar".

Sometimes it is better to "spanishize the words", as is "claimear", which on the other hand any player of minecraft in spanish understands.

Is there a problem with it? If you think it is not correct, modify the translation to leave only the new part.

**Comment by LlmDl** [comment]
I don't see it as a problem but I defer to the expertise of people who know the language. You are putting in the effort of translating and submitting the PR so you can make that call. If someone else that knows spanish has a problem with it they can submit their own PR and then it can be discussed.

**Pull request merged**
