### PR TITLE
v0.91.4.3

### PR DESCRIPTION
**Pull request by WolfLeader116**
- Town list is displayed in pages
    - Town list takes a page argument

Now, /town list won't fill your entire chat log with the small, 1 person towns as you'll start at the largest towns, then work your way down to the small ones as you increase the page number. Works similarly to /help <page>.

### CODE REVIEW

**Comment by WolfLeader116** [comment]
The es-mx and spanish yml files (possibly all language files) may need to be tweaked as I wasn't sure of the translations or where in the file the two new nodes should go.

**Comment by LlmDl** [comment]
This is really great, I've wanted to get to doing this for a while, but can you resubmit your PR in a way that doesn't completely replace the TownCommand.java and other files? It's very difficult to spot the differences otherwise.

**Comment by WolfLeader116** [comment]
I tried to get it to commit normally, but couldn't figure out the issue. It turns out that the language files are not in UTF-8 encoding, so I was unable to do anything about those as GitHub and Eclipse both forced me to change the encoding for whatever reason, and Eclipse was acting up with TownCommand.java, so I ended up just doing it in GitHub, but the issue is that now I've got 6 different commits in what should have only been one, so should I just do a pull request for that instead? I'm not sure why the entire file is being deleted and replaced, I've never encountered this before...

**Comment by LlmDl** [comment]
Can you get me the differences between the files on pastebin.com or something if you cannot submit a PR without overwriting the entire files. I'll make sure you receive credit for this in teh changelog regardless.

**Comment by WolfLeader116** [comment]
http://pastebin.com/rnxyFb4g

That should be the only changes. :) I did some pretty extensive testing and couldn't cause any errors, so it should be good.

**Comment by LlmDl** [comment]
And it's in, thank you for your contribution, I took your code and applied it to the /nation list command as well.

**Pull request closed without merging**
